/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas_ABCC;

import conexionPostgreSQL.Conexion;
import java.net.URL;
import java.sql.Connection;
import javax.swing.ImageIcon;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author marin
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        iconoEnBD();
    }
    public void iconoEnBD(){
        
        URL url = getClass().getResource("/imagenes/icono_bd.png"); 
        ImageIcon icono = new ImageIcon(url);  
        setIconImage(icono.getImage());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_princ_ventaIni = new javax.swing.JPanel();
        botonControlLibro = new javax.swing.JButton();
        botonConsultas = new javax.swing.JButton();
        botonReportes = new javax.swing.JButton();
        botonGraficas = new javax.swing.JButton();
        label_menu_principal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_princ_ventaIni.setBackground(new java.awt.Color(153, 153, 255));

        botonControlLibro.setBackground(new java.awt.Color(102, 255, 204));
        botonControlLibro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonControlLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/control de acceso_.png"))); // NOI18N
        botonControlLibro.setText("CONTROL DE LIBROS");
        botonControlLibro.setHideActionText(true);
        botonControlLibro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonControlLibro.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        botonControlLibro.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botonControlLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonControlLibroMouseClicked(evt);
            }
        });
        botonControlLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonControlLibroActionPerformed(evt);
            }
        });

        botonConsultas.setBackground(new java.awt.Color(102, 255, 204));
        botonConsultas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/control de consultas.png"))); // NOI18N
        botonConsultas.setText("CONSULTAS");
        botonConsultas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonConsultas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        botonConsultas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botonConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultasActionPerformed(evt);
            }
        });

        botonReportes.setText("REPORTES");
        botonReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonReportesMouseClicked(evt);
            }
        });
        botonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReportesActionPerformed(evt);
            }
        });

        botonGraficas.setText("GRÁFICAS");
        botonGraficas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGraficasActionPerformed(evt);
            }
        });

        label_menu_principal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label_menu_principal.setForeground(new java.awt.Color(255, 255, 255));
        label_menu_principal.setText("Menú Principal del Control de la Biblioteca");

        botonSalir.setText("SALIR");
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_princ_ventaIniLayout = new javax.swing.GroupLayout(panel_princ_ventaIni);
        panel_princ_ventaIni.setLayout(panel_princ_ventaIniLayout);
        panel_princ_ventaIniLayout.setHorizontalGroup(
            panel_princ_ventaIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_princ_ventaIniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_princ_ventaIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_menu_principal)
                    .addGroup(panel_princ_ventaIniLayout.createSequentialGroup()
                        .addGroup(panel_princ_ventaIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonGraficas, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonControlLibro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_princ_ventaIniLayout.setVerticalGroup(
            panel_princ_ventaIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_princ_ventaIniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_menu_principal)
                .addGap(18, 18, 18)
                .addGroup(panel_princ_ventaIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_princ_ventaIniLayout.createSequentialGroup()
                        .addComponent(botonControlLibro)
                        .addGap(15, 15, 15)
                        .addComponent(botonConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonGraficas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_princ_ventaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_princ_ventaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonControlLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonControlLibroActionPerformed

    }//GEN-LAST:event_botonControlLibroActionPerformed

    private void botonConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConsultasActionPerformed

    private void botonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonReportesActionPerformed

    private void botonGraficasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGraficasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGraficasActionPerformed

    private void botonControlLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonControlLibroMouseClicked
        Ventana v = new Ventana(); 
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonControlLibroMouseClicked

    private void botonReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReportesMouseClicked
            // TODO add your handling code here:
        Conexion con = new Conexion();
        Connection conexion = con.getConnection();
        try {
            String ruta= System.getProperty("user.dir")+"/src/reporte/report2.jasper";
            JasperReport jr = (JasperReport)JRLoader.loadObjectFromFile(ruta);
            JasperPrint pt = JasperFillManager.fillReport(ruta, null, conexion);
            JasperViewer jv = new JasperViewer(pt,false);
            jv.setVisible(true);
        } catch (Exception e) {
            System.out.println("Error"+e.getMessage());
        }   
    }//GEN-LAST:event_botonReportesMouseClicked

    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultas;
    private javax.swing.JButton botonControlLibro;
    private javax.swing.JButton botonGraficas;
    private javax.swing.JButton botonReportes;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_menu_principal;
    private javax.swing.JPanel panel_princ_ventaIni;
    // End of variables declaration//GEN-END:variables
}
